<?php
/**
 *
 * Date: 2018/12/14
 * Time: 14:56
 */

namespace Tests\Feature;

use App\Lib\Lock;
use Illuminate\Support\Facades\Redis;
use Tests\TestCase;

class DemoTest extends TestCase
{
    protected $demoData = false;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->demoData = true;
    }

    /**
     * @author cxr
     * @group dev
     */
    public function testDemo() //命名格式 testXXX
    {
        $this->assertTrue($this->demoData);
    }

    /**
     * @group demo
     */
    public function testLock()
    {
        $lock = Lock::getInstance();
        $res = $lock->lock('demo', 10);
        $lock->unlock('demo');
        $this->assertTrue($res);
    }
}